Update test-build.yml

diff --git a/.github/workflows/test-build.yml b/.github/workflows/test-build.yml
--- a/.github/workflows/test-build.yml
+++ b/.github/workflows/test-build.yml
@@ -152,23 +152,30 @@ jobs:
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
         echo "FILE_TIME=$(date "+%Y年%m月%d日-%H点")" >> $GITHUB_ENV
         echo "TAG_TIME=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
-
+        if [ "$status" != "success" ]; then
+          exit 1
+        fi
     - name: 保存编译日志
-      if: steps.compile.outputs.status != 'success'  # 如果编译失败 上传错误日志文件
+      if: failure()  # 如果编译失败 上传错误日志文件
       uses: actions/upload-artifact@main
       with:
         name: build-log
         path: openwrt/build.log
 
     - name: TG推送编译失败日志
-      if: steps.compile.outputs.status != 'success'
+      if: failure()
       run: |
         cd openwrt
-        grep -i "error" -C 10 build.log > error_messages.txt  # 保存错误日志
+        # 先提取包含 error 关键字及上下文的内容
+        grep -i "error" -C 10 build.log > error_messages.txt
+    
+        # 获取最后 4000 个字符，保证是整行
+        tail -c 4000 error_messages.txt | awk 'NR==1{sub(/^[^\n]*\n/, "")} 1' > error_tail.txt
+    
         while IFS= read -r line; do
           curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
-               -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=🔥编译失败！错误详情：%0A$line"
-        done < error_messages.txt
+               -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=🔥编译失败！日志结尾：%0A$line"
+        done < error_tail.txt
 
     - name: 查看磁盘使用情况
       if: (!cancelled())
@@ -183,7 +190,7 @@ jobs:
 
     - name: 整理编译好的固件
       id: organize
-      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
+      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
       run: |
         cd openwrt/bin/targets/*/*
         rm -rf packages && mkdir packages
