Update test-build.yml

diff --git a/.github/workflows/test-build.yml b/.github/workflows/test-build.yml
--- a/.github/workflows/test-build.yml
+++ b/.github/workflows/test-build.yml
@@ -6,7 +6,7 @@
 # Blog: https://p3terx.com
 #=================================================
 
-name: TEST-OpenWrt-x86_64-builder
+name: OpenWrt-x86_64-builder
 
 on:
   repository_dispatch:
@@ -127,12 +127,12 @@ jobs:
       run: |
         cd openwrt
         echo -e "$(nproc) thread compile"
-        make -j$(nproc) V=s |& tee build.log || make -j1 V=s |& tee -a build.log
+        make -j$(nproc) || make -j1 || make -j1 V=s | tee build.log
         compile_status=$?
-        if [ "$compile_status" -ne 0 ]; then
-          echo "status=failed" >> $GITHUB_OUTPUT
-          exit 1
-        fi
+          if [ "$compile_status" -ne 0 ]; then
+            echo "status=failed" >> $GITHUB_OUTPUT
+            exit 1
+          fi
         echo "status=success" >> $GITHUB_OUTPUT
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
@@ -145,7 +145,7 @@ jobs:
       uses: actions/upload-artifact@main
       with:
         name: build-log
-        path: build.log
+        path: openwrt/build.log
 
     - name: TG推送编译失败日志
       if: steps.compile.outputs.status != 'success'
