Update test-build.yml

diff --git a/.github/workflows/test-build.yml b/.github/workflows/test-build.yml
--- a/.github/workflows/test-build.yml
+++ b/.github/workflows/test-build.yml
@@ -127,7 +127,12 @@ jobs:
       run: |
         cd openwrt
         echo -e "$(nproc) thread compile"
-        make -j$(nproc) > build.log 2>&1 || make -j1 V=s >> build.log 2>&1
+        make -j$(nproc) V=s |& tee build.log || make -j1 V=s |& tee -a build.log
+        compile_status=$?
+        if [ "$compile_status" -ne 0 ]; then
+          echo "status=failed" >> $GITHUB_OUTPUT
+          exit 1
+        fi
         echo "status=success" >> $GITHUB_OUTPUT
         grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
@@ -143,7 +148,7 @@ jobs:
         path: build.log
 
     - name: TG推送编译失败日志
-      if: steps.compile.outcome != 'success'
+      if: steps.compile.outputs.status != 'success'
       run: |
         grep -i "error" -C 10 build.log > error_messages.txt  # 保存错误日志
         while IFS= read -r line; do
@@ -157,7 +162,7 @@ jobs:
 
     - name: 上传bin压缩目录
       uses: actions/upload-artifact@main
-      if: steps.compile.outcome == 'success' && env.UPLOAD_BIN_DIR == 'true'
+      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
       with:
         name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
         path: openwrt/bin/packages/x86_64
@@ -179,7 +184,7 @@ jobs:
         echo "status=success" >> $GITHUB_OUTPUT
     - name: 上传固件到github
       uses: actions/upload-artifact@main
-      if: steps.compile.outcome == 'success' && !cancelled()
+      if: steps.compile.outputs.status == 'success' && !cancelled()
       with:
         name: OpenWrt_x86_64_6.6${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
         path: ${{ env.FIRMWARE }}
@@ -187,7 +192,7 @@ jobs:
 
     - name: 上传固件到WT网盘
       id: wetransfer
-      if: steps.compile.outcome == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
+      if: steps.compile.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
       run: |
         curl -fsSL https://raw.githubusercontent.com/Mikubill/transfer/master/install.sh | sh
         ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
